# @package _group_

stream_sizes: [1]
has_dynamic_features: [false]
stream_weights: [1]

netG:
  _target_: nnsvs.model.LSTMRNN
  in_dim: 212
  out_dim: 1
  hidden_dim: 128
  num_layers: 6
  bidirectional: true
  dropout: 0.5
