# @package _group_

stream_sizes: [1]
has_dynamic_features: [false]
stream_weights: [1]

netG:
  _target_: nnsvs.model.FeedForwardNet
  in_dim: 212
  out_dim: 1
  hidden_dim: 512
  num_layers: 6
  dropout: 0.5
